# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBCyQnXFJKynLGYIkP72BWkXUjTd7S4Z
"""



import yfinance as yf
import pandas as pd
import requests
from openpyxl.styles import Font, Alignment
from datetime import datetime
import pytz
from google.colab import files

# News API 키 (사용자 키 입력 필요)
NEWS_API_KEY = "17df4ce9e1a74990a4414f4a369876de"

# 1. 대상 티커 설정 (원하는 종목을 계속 추가할 수 있습니다)
tickers = {
    "S&P500": "^GSPC",
    "나스닥": "^IXIC",
    "코스피": "^KS11",
    "코스닥": "^KQ11",
    "USD/KRW": "KRW=X",
    "비트코인": "BTC-USD",
    "삼성전자": "005930.KS",
    "KODEX 200위클리커버드콜": "498400.KS",
    "SK하이닉스": "000660.KS",
    "현대차": "005380.KS"
}

combined_data = []

for name, symbol in tickers.items():
    t = yf.Ticker(symbol)
    # 최근 5일 데이터 (전일가 계산용)
    hist_short = t.history(period="5d")
    # 전체 히스토리 (역대 최고가 계산용)
    hist_max = t.history(period="max")

    current_price = "-"
    prev_price = "-"
    change_amount = "-"
    daily_change = "-"
    ath_change = "-"
    ath_value = "-"
    ath_date = "-"

    if not hist_short.empty and len(hist_short) >= 2:
        curr = hist_short["Close"].iloc[-1]
        prev = hist_short["Close"].iloc[-2]
        current_price = round(curr, 2)
        prev_price = round(prev, 2)

        # 변동폭 (현재가 - 전일가)
        diff = curr - prev
        change_amount = round(diff, 2)

        # 어제대비 변동률
        d_chg = (diff / prev) * 100
        daily_change = f"{round(d_chg, 2)}%"

        # 역대 최고가 정보 추출
        if not hist_max.empty:
            ath_series = hist_max["Close"]
            ath_val = ath_series.max()
            ath_value = round(ath_val, 2)
            ath_date = ath_series.idxmax().strftime('%Y-%m-%d')
            # 최고가 대비 현재 위치
            a_chg = ((curr - ath_val) / ath_val) * 100
            ath_change = f"{round(a_chg, 2)}%"

    combined_data.append({
        "항목": name,
        "현재가/지수": current_price,
        "전일가/지수": prev_price,
        "어제대비": daily_change,
        "변동폭": change_amount,
        "역대최고가대비": ath_change,
        "역대최고가": ath_value,
        "최고가 기록일": ath_date
    })

df_market = pd.DataFrame(combined_data)

# 2. 뉴스 가져오기
def get_korean_news(api_key):
    url = f"https://newsapi.org/v2/top-headlines?country=kr&category=business&pageSize=3&apiKey={api_key}"
    try:
        res = requests.get(url)
        data = res.json()
        if data.get('status') == 'ok':
            return [{"제목": a.get('title'), "링크": a.get('url')} for a in data.get('articles', [])]
    except: pass
    return []

news_list = get_korean_news(NEWS_API_KEY)
df_news = pd.DataFrame(news_list if news_list else [{"제목": "뉴스 없음", "링크": "-"}])

# 3. 엑셀 생성 및 다운로드
file_name = "market_report_with_stock.xlsx"
with pd.ExcelWriter(file_name, engine="openpyxl") as writer:
    df_market.to_excel(writer, sheet_name="시장 및 종목지수", index=False, startrow=1)
    df_news.to_excel(writer, sheet_name="최신뉴스", index=False)

    wb = writer.book
    ws = wb["시장 및 종목지수"]
    kst = pytz.timezone('Asia/Seoul')
    now_kst = datetime.now(kst).strftime("%Y-%m-%d %H:%M:%S")
    ws['A1'] = f"기준 시간: {now_kst}"
    ws.merge_cells('A1:H1')
    ws['A1'].font = Font(bold=True)

    # 열 너비 설정
    for col, width in zip(['A','B','C','D','E','F','G','H'], [15, 18, 18, 15, 15, 20, 18, 20]):
        ws.column_dimensions[col].width = width

    # 정렬 및 서식 설정
    right_alignment = Alignment(horizontal='right')
    center_alignment = Alignment(horizontal='center')

    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        for cell_idx in range(1, 7):
            row[cell_idx].alignment = right_alignment
        row[7].alignment = center_alignment

        if row[0].row >= 3:
            for idx in [1, 2, 4, 6]:
                if isinstance(row[idx].value, (int, float)):
                    row[idx].number_format = '#,##0.00'

print(f"엑셀 생성 완료! 종목이 포함된 리포트가 생성되었습니다.")
files.download(file_name)